name: Step 3 # Configuração do projeto Django e população de dados de teste do banco

on:
  push:
    branches:
      - "build-octofit-app"
    paths:
      - "octofit-tracker/backend/octofit_tracker/**"

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_4_FILE: ".github/steps/4-setup-django-rest-framework.md"

jobs:
  find_exercise:
    name: Encontrar Issue do Exercício
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.0

  check_step_work:
    name: Verificar trabalho da etapa
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      - name: Encontrar último comentário
        id: find-last-comment
        uses: peter-evans/find-comment@v3
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          direction: last

      - name: Atualizar comentário - verificando trabalho
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
          file: exercise-toolkit/markdown-templates/step-feedback/checking-work.md
          edit-mode: replace

      # INÍCIO: Verificar exercício prático
      - name: Verificar octofit_db settings.py
        id: check-octofit-db-settings
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: octofit-tracker/backend/octofit_tracker/settings.py
          keyphrase: 'octofit_db'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Verificar djongo settings.py
        id: check-djongo-settings
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: octofit-tracker/backend/octofit_tracker/settings.py
          keyphrase: 'djongo'
          minimum-occurrences: 2
          case-sensitive: false

      - name: Verificar populate_db.py
        id: check-populate-db
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: octofit-tracker/backend/octofit_tracker/management/commands/populate_db.py
          keyphrase: 'Populate the octofit_db database with test data'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Atualizar comentário - resultados da etapa
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
          edit-mode: replace
          file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          vars: |
            step_number: 3
            results_table:
              - description: "Verificar settings.py para octofit_db"
                passed: ${{ steps.check-octofit-db-settings.outcome == 'success' }}
              - description: "Verificar settings.py para djongo"
                passed: ${{ steps.check-djongo-settings.outcome == 'success' }}
              - description: "Verificar populate_db.py para criação de dados de teste"
                passed: ${{ steps.check-populate-db.outcome == 'success' }}

      # FIM: Verificar exercício prático

      - name: Falhar job se nem todas as verificações passaram
        if: contains(steps.*.outcome, 'failure')
        run: exit 1      

  post_next_step_content:
    name: Postar conteúdo da próxima etapa
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      - name: Criar comentário - etapa finalizada
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 4

      - name: Criar comentário - adicionar conteúdo da etapa
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_4_FILE }}

      - name: Criar comentário - observando progresso
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Desabilitar workflow atual e habilitar o próximo
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "Step 4"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
